// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyarpkgqzushgjnwquxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5YXJwa2dxenVzaGdqbndxdXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTMxODcsImV4cCI6MjA3MDAyOTE4N30.6-shDOGBlIMzKqncDmrMEPbFr8-lHHw9e6CpX9ew2Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});